In [1]:
import numpy as np                
import pandas as pd               
from sklearn.model_selection import train_test_split  
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import matplotlib.pyplot as plt  
import platform

In [3]:
df = pd.read_csv('usa_housing.csv')
df.head()

,Price,Bedrooms,Bathrooms,SquareFeet,YearBuilt,GarageSpaces,LotSize,ZipCode,CrimeRate,SchoolRating
0,221958,1,1.9,4827,1979,2,1.45,82240,48.60,5
1,771155,2,2.0,1035,1987,2,1.75,74315,92.03,9
2,231932,1,3.0,2769,1982,1,1.46,79249,52.08,3
3,465838,3,3.3,2708,1907,3,1.62,80587,61.65,1
4,359178,4,3.4,1175,1994,2,0.74,20756,15.66,4

In [5]:
df = df[(df['YearBuilt'] > 2015) & (df['CrimeRate'] < 40)]
df.head()

,Price,Bedrooms,Bathrooms,SquareFeet,YearBuilt,GarageSpaces,LotSize,ZipCode,CrimeRate,SchoolRating
9,737147,3,2.6,4191,2017,0,1.65,66549,37.60,3
33,586232,4,1.3,3854,2021,2,1.39,30103,26.93,2
112,616588,2,1.2,3872,2016,0,0.17,61112,20.98,8
119,979858,5,3.8,4307,2020,0,0.38,41822,37.14,4
189,161087,5,2.4,964,2021,1,0.24,34022,12.80,3

In [6]:
X_sqft = df[['SquareFeet']].values
y_price = df['Price'].values
X_sqft.shape, y_price.shape

((10, 1), (10,))

In [7]:
# 데이터 스케일링
scaler_X = MinMaxScaler()

X_scaled = scaler_X.fit_transform(X_sqft).flatten()
print(X_scaled[:5])

[0.96530063 0.86449297 0.86987736 1.         0.        ]

In [8]:
# 데이터 쪼개기
# 1차 분할 
X_train_val, X_test, y_train_val, y_test = train_test_split(
    X_scaled, y_price, test_size=0.2, random_state=42
)

X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_val, y_train_val, test_size=0.25, random_state=42
)
print(f"전체 주택 데이터 수: {len(X_scaled)}채")
print(f"훈련(Train)용 주택: {len(X_train)}채")
print(f"검증(Valid)용 주택: {len(X_valid)}채")
print(f"테스트(Test)용 주택: {len(X_test)}채")

전체 주택 데이터 수: 10채
훈련(Train)용 주택: 6채
검증(Valid)용 주택: 2채
테스트(Test)용 주택: 2채