In [3]:
import pandas as pd

df = pd.read_csv('usa_housing.csv')

df.head()

,Price,Bedrooms,Bathrooms,SquareFeet,YearBuilt,GarageSpaces,LotSize,ZipCode,CrimeRate,SchoolRating
0,221958,1,1.9,4827,1979,2,1.45,82240,48.60,5
1,771155,2,2.0,1035,1987,2,1.75,74315,92.03,9
2,231932,1,3.0,2769,1982,1,1.46,79249,52.08,3
3,465838,3,3.3,2708,1907,3,1.62,80587,61.65,1
4,359178,4,3.4,1175,1994,2,0.74,20756,15.66,4

In [5]:
df = df[df['Bedrooms'] >3 ]

df.head()

,Price,Bedrooms,Bathrooms,SquareFeet,YearBuilt,GarageSpaces,LotSize,ZipCode,CrimeRate,SchoolRating
4,359178,4,3.4,1175,1994,2,0.74,20756,15.66,4
10,621430,4,2.3,3765,1979,2,0.96,44503,55.01,9
13,275203,4,1.4,1672,1924,1,1.49,84069,27.38,2
14,291335,4,1.4,2052,1981,1,0.26,15249,92.83,6
18,164820,4,1.3,3421,1958,1,1.76,63363,99.24,9

In [ ]:
X = df[['CrimeRate']].values
y = df['Price'].values

X.shape, y.shape

((123, 1), (123,))

In [9]:
from sklearn.model_selection import train_test_split # train set, validation set, test set 분리

In [ ]:
# test
X_train_tmp, X_test, y_train_tmp, y_test = train_test_split(
    X, y, test_size = 0.2, random_state=42
)


# valid
X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_tmp, y_train_tmp, test_size=0.25, random_state=42
)

print('전체 : ',X.shape)
print('훈련 세트 : ', X_train.shape)
print('검증 세트 : ', X_valid.shape)
print('테스트 세트 : ', X_test.shape)

전체 :  (123, 1)
훈련 세트 :  (78, 1)
검증 세트 :  (20, 1)
테스트 세트 :  (25, 1)

In [13]:
from sklearn.preprocessing import StandardScaler

In [ ]:
ss1 = StandardScaler()

X_scaled = ss1.fit_transform(X).flatten()
print(X_scaled[:1], X_scaled.shape)

[-1.17020113] (123,)